# Generated by Django 4.0.5 on 2022-07-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='money',
            field=models.IntegerField(default=500000),
        ),
    ]
