# Generated by Django 4.0.5 on 2022-07-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_useraccount_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NOT_FOUND', max_length=265)),
                ('price', models.IntegerField(default=0)),
                ('data', models.JSONField(default={'data': 'none'})),
            ],
        ),
    ]
