# Generated by Django 4.0.5 on 2022-08-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_shorting_money_useraccount_shorted_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='shorted_money',
        ),
    ]
