# Generated by Django 4.0.5 on 2022-07-29 23:29

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='data',
            field=models.JSONField(default=market.models.Stock.default_data),
        ),
    ]
