# Generated by Django 4.0.5 on 2022-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_stock_name_alter_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='data',
            field=models.JSONField(default={'data': 'none'}),
        ),
    ]
