# Generated by Django 4.0.5 on 2022-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_stock_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='stocks',
            field=models.JSONField(default={}),
        ),
    ]
